Repository makerspace/memberbooth, pull requests merged in 2020-02, with the labels that each got.

#43 Development flag defaults
  memberbooth.py
  src/util/parser.py
Labels: development nice-ity, enhancement

#45 Compound label implementation
  src/gui/design.py
  src/gui/event.py
  src/gui/states.py
  src/label/creator.py
Labels: enhancement

#47 Serial port disconnect/reconnect handling
  memberbooth.py
  src/gui/design.py
  src/gui/event.py
  src/gui/states.py
  src/util/key_reader.py
Labels: bug, stability
